seed: 77

pp:
  sampling_ratio: 0.05
cg:
  item_mf:
    n_epochs: 20
    n_factors: 256
    lr: 0.3
    train_batch_size: 131072
  item_mf_last:
    gen_cand_topk: 40
  item_mf_seq:
    gen_cand_topk: 40
  user_mf:
    n_epochs: 100
    n_factors: 256
    lr: 0.01
    train_batch_size: 131072
    user_min_inters: 20
    gen_cand_topk: 40
  item2vec:
    lr: 0.1
    window: 15
    vector_size: 32
    sg: 1
    epochs: 10
    seed: 77
    negative: 20
    min_count: 1
    gen_cand_topk: 30
ranker:
  features:
  - last_inter_score_selected
  - last_buy_score_selected
  - last_click_score_selected
  - last_cart_score_selected
  - last_order_score_selected
  - item_cf_s012_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_selected
  - item_cf_s012_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_selected
  - item_cf_s012_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_selected
  - item_cf_s12_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_selected
  - item_cf_s12_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_selected
  - item_cf_s12_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_selected
  - item_cf_s0_t0_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_selected
  - item_cf_s0_t0_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_selected
  - item_cf_s0_t0_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_selected
  - item_cf_s0_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_selected
  - item_cf_s0_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_selected
  - item_cf_s0_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_selected
  - item_cf_s0_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_selected
  - item_cf_s0_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_selected
  - item_cf_s0_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_selected
  - item_cf_s12_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_selected
  - item_cf_s12_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_selected
  - item_cf_s12_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_selected
  - item_cf_s012_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_sum_score_selected
  - item_cf_s012_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_last_score_selected
  - item_cf_s012_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_count_score_selected
  - item_cf_s12_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_sum_score_selected
  - item_cf_s12_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_last_score_selected
  - item_cf_s12_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_count_score_selected
  - item_cf_s012_t012_apFalse_tdTrue_trTrue_iifTrue_fFalse_sum_score_selected
  - item_cf_s012_t012_apFalse_tdTrue_trTrue_iifTrue_fFalse_last_score_selected
  - item_cf_s012_t012_apFalse_tdTrue_trTrue_iifTrue_fFalse_count_score_selected
  - item_mf_last_score_selected
  - item_mf_seq_score_selected
  - item2vec_last_score_selected
  - item2vec_seq_score_selected
  - user_mf_score_selected
  - last_inter_score
  - last_inter_score_rank
  - last_inter_score_min_rank
  - last_buy_score
  - last_buy_score_rank
  - last_buy_score_min_rank
  - last_click_score
  - last_click_score_rank
  - last_click_score_min_rank
  - last_cart_score
  - last_cart_score_rank
  - last_cart_score_min_rank
  - last_order_score
  - last_order_score_rank
  - last_order_score_min_rank
  - item_cf_s012_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score
  - item_cf_s012_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_rank
  - item_cf_s012_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_min_rank
  - item_cf_s012_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score
  - item_cf_s012_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_rank
  - item_cf_s012_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_min_rank
  - item_cf_s012_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score
  - item_cf_s012_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_rank
  - item_cf_s012_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_min_rank
  - item_cf_s12_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score
  - item_cf_s12_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_rank
  - item_cf_s12_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_min_rank
  - item_cf_s12_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score
  - item_cf_s12_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_rank
  - item_cf_s12_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_min_rank
  - item_cf_s12_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score
  - item_cf_s12_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_rank
  - item_cf_s12_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_min_rank
  - item_cf_s0_t0_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score
  - item_cf_s0_t0_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_rank
  - item_cf_s0_t0_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_min_rank
  - item_cf_s0_t0_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score
  - item_cf_s0_t0_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_rank
  - item_cf_s0_t0_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_min_rank
  - item_cf_s0_t0_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score
  - item_cf_s0_t0_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_rank
  - item_cf_s0_t0_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_min_rank
  - item_cf_s0_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score
  - item_cf_s0_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_rank
  - item_cf_s0_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_min_rank
  - item_cf_s0_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score
  - item_cf_s0_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_rank
  - item_cf_s0_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_min_rank
  - item_cf_s0_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score
  - item_cf_s0_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_rank
  - item_cf_s0_t12_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_min_rank
  - item_cf_s0_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score
  - item_cf_s0_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_rank
  - item_cf_s0_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_min_rank
  - item_cf_s0_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score
  - item_cf_s0_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_rank
  - item_cf_s0_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_min_rank
  - item_cf_s0_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score
  - item_cf_s0_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_rank
  - item_cf_s0_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_min_rank
  - item_cf_s12_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score
  - item_cf_s12_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_rank
  - item_cf_s12_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_sum_score_min_rank
  - item_cf_s12_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score
  - item_cf_s12_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_rank
  - item_cf_s12_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_last_score_min_rank
  - item_cf_s12_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score
  - item_cf_s12_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_rank
  - item_cf_s12_t012_apTrue_tdTrue_trFalse_iifTrue_fFalse_count_score_min_rank
  - item_cf_s012_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_sum_score
  - item_cf_s012_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_sum_score_rank
  - item_cf_s012_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_sum_score_min_rank
  - item_cf_s012_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_last_score
  - item_cf_s012_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_last_score_rank
  - item_cf_s012_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_last_score_min_rank
  - item_cf_s012_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_count_score
  - item_cf_s012_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_count_score_rank
  - item_cf_s012_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_count_score_min_rank
  - item_cf_s12_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_sum_score
  - item_cf_s12_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_sum_score_rank
  - item_cf_s12_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_sum_score_min_rank
  - item_cf_s12_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_last_score
  - item_cf_s12_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_last_score_rank
  - item_cf_s12_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_last_score_min_rank
  - item_cf_s12_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_count_score
  - item_cf_s12_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_count_score_rank
  - item_cf_s12_t012_apTrue_tdTrue_trTrue_iifTrue_fTrue_count_score_min_rank
  - item_cf_s012_t012_apFalse_tdTrue_trTrue_iifTrue_fFalse_sum_score
  - item_cf_s012_t012_apFalse_tdTrue_trTrue_iifTrue_fFalse_sum_score_rank
  - item_cf_s012_t012_apFalse_tdTrue_trTrue_iifTrue_fFalse_sum_score_min_rank
  - item_cf_s012_t012_apFalse_tdTrue_trTrue_iifTrue_fFalse_last_score
  - item_cf_s012_t012_apFalse_tdTrue_trTrue_iifTrue_fFalse_last_score_rank
  - item_cf_s012_t012_apFalse_tdTrue_trTrue_iifTrue_fFalse_last_score_min_rank
  - item_cf_s012_t012_apFalse_tdTrue_trTrue_iifTrue_fFalse_count_score
  - item_cf_s012_t012_apFalse_tdTrue_trTrue_iifTrue_fFalse_count_score_rank
  - item_cf_s012_t012_apFalse_tdTrue_trTrue_iifTrue_fFalse_count_score_min_rank
  - item_mf_last_score
  - item_mf_last_score_rank
  - item_mf_last_score_min_rank
  - item_mf_seq_score
  - item_mf_seq_score_rank
  - item_mf_seq_score_min_rank
  - item2vec_last_score
  - item2vec_last_score_rank
  - item2vec_last_score_min_rank
  - item2vec_seq_score
  - item2vec_seq_score_rank
  - item2vec_seq_score_min_rank
  - user_mf_score
  - user_mf_score_rank
  - user_mf_score_min_rank
  - cand_feature_selected_num
  - cand_feature_selected_score
  - cand_feature_selected_rank
  - cand_feature_selected_min_rank
  - item_inter_num_3d
  - item_buy_num_3d
  - item_click_num_3d
  - item_cart_num_3d
  - item_order_num_3d
  - item_inter_num_7d
  - item_buy_num_7d
  - item_click_num_7d
  - item_cart_num_7d
  - item_order_num_7d
  - item_inter_num_14d
  - item_buy_num_14d
  - item_click_num_14d
  - item_cart_num_14d
  - item_order_num_14d
  - item_inter_num_21d
  - item_buy_num_21d
  - item_click_num_21d
  - item_cart_num_21d
  - item_order_num_21d
  - item_inter_rank_3d
  - item_buy_rank_3d
  - item_click_rank_3d
  - item_cart_rank_3d
  - item_order_rank_3d
  - item_inter_rank_7d
  - item_buy_rank_7d
  - item_click_rank_7d
  - item_cart_rank_7d
  - item_order_rank_7d
  - item_inter_rank_14d
  - item_buy_rank_14d
  - item_click_rank_14d
  - item_cart_rank_14d
  - item_order_rank_14d
  - item_inter_rank_21d
  - item_buy_rank_21d
  - item_click_rank_21d
  - item_cart_rank_21d
  - item_order_rank_21d
  - item_inter_ts_mean
  - item_inter_ts_min
  - item_inter_ts_max
  - item_inter_ts_std
  - item_multi_inter_prob
  - item_multi_buy_prob
  - item_multi_click_prob
  - item_multi_cart_prob
  - item_multi_order_prob
  - item_click_to_cart_prob_3d
  - item_click_to_order_prob_3d
  - item_cart_to_order_prob_3d
  - item_click_to_cart_prob_7d
  - item_click_to_order_prob_7d
  - item_cart_to_order_prob_7d
  - item_click_to_cart_prob_14d
  - item_click_to_order_prob_14d
  - item_cart_to_order_prob_14d
  - item_click_to_cart_prob_21d
  - item_click_to_order_prob_21d
  - item_cart_to_order_prob_21d
  - user_first_inter_dow
  - user_last_inter_dow
  - user_first_buy_dow
  - user_last_buy_dow
  - user_first_click_dow
  - user_last_click_dow
  - user_first_cart_dow
  - user_last_cart_dow
  - user_first_order_dow
  - user_last_order_dow
  - user_inter_num
  - user_buy_num
  - user_click_num
  - user_cart_num
  - user_order_num
  - user_inter_ts_diff_min
  - user_inter_ts_diff_mean
  - user_inter_ts_diff_std
  - user_inter_ts_diff_max
  - user_buy_ts_diff_min
  - user_buy_ts_diff_mean
  - user_buy_ts_diff_std
  - user_buy_ts_diff_max
  - user_click_ts_diff_min
  - user_click_ts_diff_mean
  - user_click_ts_diff_std
  - user_click_ts_diff_max
  - user_cart_ts_diff_min
  - user_cart_ts_diff_mean
  - user_cart_ts_diff_std
  - user_cart_ts_diff_max
  - user_order_ts_diff_min
  - user_order_ts_diff_mean
  - user_order_ts_diff_std
  - user_order_ts_diff_max
  - user_inter_ts_hour_mean
  - user_buy_ts_hour_mean
  - user_click_ts_hour_mean
  - user_cart_ts_hour_mean
  - user_order_ts_hour_mean
  - user_inter_ts_mean
  - user_inter_ts_min
  - user_inter_ts_max
  - user_inter_ts_std
  - user_ts_diff
  - user_min_all_min_ts_diff
  - user_max_all_min_ts_diff
  - user_min_all_max_ts_diff
  - user_max_all_max_ts_diff
  - user_item_first_inter_rank
  - user_item_first_buy_rank
  - user_item_first_click_rank
  - user_item_first_cart_rank
  - user_item_first_order_rank
  - user_item_last_inter_rank
  - user_item_last_buy_rank
  - user_item_last_click_rank
  - user_item_last_cart_rank
  - user_item_last_order_rank
  - user_item_is_first_inter
  - user_item_is_last_inter
  - user_item_is_first_buy
  - user_item_is_last_buy
  - user_item_is_first_click
  - user_item_is_last_click
  - user_item_is_first_cart
  - user_item_is_last_cart
  - user_item_is_first_order
  - user_item_is_last_order
